# Generated by Django 2.1.1 on 2018-09-19 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custo', models.FloatField()),
                ('tipo', models.CharField(max_length=30)),
                ('criacao', models.DateField()),
                ('modeda', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fundo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.FloatField()),
                ('id_despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Despesa')),
            ],
        ),
        migrations.CreateModel(
            name='GraficoFundo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateField()),
                ('id_fundo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Fundo')),
            ],
        ),
        migrations.CreateModel(
            name='GraficoMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital', models.FloatField()),
                ('tipo', models.CharField(max_length=30)),
                ('criacao', models.DateField()),
                ('modeda', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investimento', models.FloatField()),
                ('despesa', models.FloatField()),
                ('criacao', models.DateField()),
                ('inicio', models.DateField()),
                ('prazo', models.DateField()),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=80, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='meta',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Usuario'),
        ),
        migrations.AddField(
            model_name='investimento',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Usuario'),
        ),
        migrations.AddField(
            model_name='graficometa',
            name='id_meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Meta'),
        ),
        migrations.AddField(
            model_name='graficometa',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Usuario'),
        ),
        migrations.AddField(
            model_name='graficofundo',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Usuario'),
        ),
        migrations.AddField(
            model_name='fundo',
            name='id_investimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Investimento'),
        ),
        migrations.AddField(
            model_name='fundo',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Usuario'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Usuario'),
        ),
    ]
