# Generated by Django 2.1.2 on 2018-11-23 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20181117_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipodespesa',
            options={'ordering': ['nome'], 'verbose_name': 'Tipo de Depesa', 'verbose_name_plural': 'Tipos de Despesas'},
        ),
        migrations.RenameField(
            model_name='tipodespesa',
            old_name='tipo',
            new_name='nome',
        ),
    ]
