# Generated by Django 2.1.1 on 2018-09-28 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moeda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='DEFAULT VALUE', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDespesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoInvestimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='graficofundo',
            name='id_fundo',
        ),
        migrations.RemoveField(
            model_name='graficofundo',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='graficometa',
            name='id_meta',
        ),
        migrations.RemoveField(
            model_name='graficometa',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='criacao',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='custo',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='modeda',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='investimento',
            name='modeda',
        ),
        migrations.RemoveField(
            model_name='investimento',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='fundo',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investimento',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meta',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='GraficoFundo',
        ),
        migrations.DeleteModel(
            name='GraficoMeta',
        ),
    ]
