# Generated by Django 2.1.1 on 2018-09-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180928_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='moeda',
            name='nome',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
