# Generated by Django 2.1.1 on 2018-09-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180928_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moeda',
            name='nome',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
