# Generated by Django 2.1.1 on 2018-09-28 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180928_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='investimento',
            name='id_tipoInvestimento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.TipoInvestimento'),
        ),
    ]
