# Generated by Django 2.1.2 on 2018-10-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20181025_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='nome',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='investimento',
            name='nome',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='meta',
            name='nome',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='moeda',
            name='nome',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tipoinvestimento',
            name='tipo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
