# Generated by Django 2.1.2 on 2018-10-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20181026_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundo',
            name='nome',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
